build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_REFERENCE: "ffmpeg/3.3.3"
    CONAN_USERNAME: "vtpl1"
    CONAN_LOGIN_USERNAME: "vtpl1"
    CONAN_CHANNEL: "stable"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
    CONAN_UPLOAD: "https://api.bintray.com/conan/vtpl1/conan-ffmpeg"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
          CONAN_ARCHS: "x86_64"
          CONAN_CURRENT_PAGE="x86_64"

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/;C:/msys64
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory
  
  
test_script:
  - python build.py
